# Generated by Django 4.0.3 on 2022-04-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPost', '0003_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posteos'),
        ),
    ]
